site_name: SPA Docs
site_url: http://MetaBake.org
repo_url: http://MetaBake.org
pages:
   - Home/ B.M.: index.md

   - CSS Fix: css.md
   - Blog Example: blog.md
   - SPA-Router: router.md
   - App Store: appStore.md
   - More examples: more.md

   - Resources: res.md
   - About: about.md

theme: readthedocs
