site_name: SPA Docs
site_url: http://MetaBake.org
repo_url: http://MetaBake.org
pages:
   - Home/ B.M.: index.md

   - CSS: css.md
   - Blog Example: blog.md
   - SPA-Router: router.md

   - Electron: elect.md
   - PhoneGap: phoneGap.md
   - More: more.md

   - Next Step: next.md
   - Resources: res.md
   - About: about.md

theme: readthedocs
