site_name: SPA Docs
site_url: http://MetaBake.org
repo_url: http://MetaBake.org
copyright: (copyright MetaBake | cekvenich)
pages:
   - Home: index.md
   - App Store: app-store.md
   - About: about.md

theme: readthedocs
