site_name: SPA Docs
site_url: http://MetaBake.org
repo_url: http://MetaBake.org
copyright: (copyright MetaBake | cekvenich)
pages:
   - Home/ App Store: index.md
   - SPA-Router: router.md
   - Blog Example: blog.md
   - App Store: phonegap.md
   - Other examples: other.md
   - Resources: res.md
   - About: about.md

theme: readthedocs
